openapi: 3.0.3
info:
  title: dip-mds
  description: DIP-Massendatenschnittstelle
  version: DIP-MDS 2.1
tags:
  - name: MDSProviderV2_1
    description: Einreichen von Massendatenlieferungen
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Authorization token (Bearer <token>)"
security:
  - BearerAuth: [ ]
paths:
  /dip/md/v2_1/start/{fachverfahren}:
    post:
      tags:
        - MDSProviderV2_1
      summary: Anfordern einer Datentransfernummer und Einleiten einer Massendatenlieferung
      description: >-
        Anfordern einer Datentransfernummer zur Identifikation der Lieferung und Einleiten einer Massendatenlieferung
      operationId: einreichungAnmelden
      parameters:
        - name: fachverfahren
          in: path
          description: 'Das Ziel-Fachverfahren'
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Datentransfer erfolgreich initiiert
          content:
            text/plain:
              schema:
                type: string
        '401':
          description: Ungültiger Authorization Header
        '404':
          description: Zielfachverfahren nicht gefunden
        '429':
          description: Der Client hat zu viele Anfragen in einem bestimmten Zeitraum gesendet
        '500':
          description: Interner Fehler
  /dip/md/v2_1/{datentransfernummer}/xml:
    put:
      tags:
        - MDSProviderV2_1
      summary: Einreichung des XML
      description: >-
        Einreichung der Daten-XML unter Angabe einer Datentransfernummer
      operationId: massendatenEinreichen
      parameters:
        - name: datentransfernummer
          in: path
          description: 'Die Datentransfernummer, die die Transaktion identifiziert'
          required: true
          schema:
            type: string
      requestBody:
        description: >-
          Einreichung der Daten-XML unter Angabe einer Datentransfernummer
        content:
          application/octet-stream:
            schema:
              type: InputStream
      responses:
        '200':
          description: Einreichung erfolgreich
        '400':
          description: Ungültige Datentransfernummer
        '401':
          description: Ungültiger Authorization Header
        '409':
          description: Ungültige Schnittstellen Version
        '410':
          description: Datentransfer wurde bereits beendet
        '424':
          description: Der Datenübermittler ist dem Vorgang nicht zugeordnet
        '500':
          description: Interner Fehler
  /dip/md/v2_1/{datentransfernummer}/attachment:
    put:
      tags:
        - MDSProviderV2_1
      summary: Einreichung zusätzlicher Anhänge
      description: >-
        Einreichung zusätzlicher Anhänge unter Angabe einer Datentransfernummer
      operationId: anhangEinreichen
      parameters:
        - name: datentransfernummer
          in: path
          description: 'Die Datentransfernummer, die die Transaktion identifiziert'
          required: true
          schema:
            type: string
      requestBody:
        description: >-
          Einreichung zusätzlicher Anhänge unter Angabe einer Datentransfernummer
        content:
          application/octet-stream:
            schema:
              type: InputStream
      responses:
        '200':
          description: Einreichung erfolgreich
        '400':
          description: Ungültige Datentransfernummer
        '401':
          description: Ungültiger Authorization Header
        '409':
          description: Ungültige Schnittstellen Version
        '424':
          description: Der Datenübermittler ist dem Vorgang nicht zugeordnet
        '500':
          description: Interner Fehler
  /dip/md/v2_1/{datentransfernummer}/finish:
    patch:
      tags:
        - MDSProviderV2_1
      summary: Erklärung, dass die Massendatenlieferung abgeschlossen ist
      description: >-
        Erklärung der Fertigstellung der Massendatenlieferung
      operationId: einreichungBeenden
      parameters:
        - name: datentransfernummer
          in: path
          description: 'Die Datentransfernummer, die die Transaktion identifiziert'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Anfrage erfolgreich
        '400':
          description: Ungültige Datentransfernummer
        '401':
          description: Ungültiger Authorization Header
        '409':
          description: Ungültige Schnittstellen Version
        '410':
          description: Datentransfer wurde bereits beendet
        '424':
          description: Der Datenübermittler ist dem Vorgang nicht zugeordnet
        '500':
          description: Interner Fehler
  /dip/md/v2_1/{datentransfernummer}/abort:
    patch:
      tags:
        - MDSProviderV2_1
      summary: Abbruch der laufenden Übertragung und Verwerfen der bisher übertragenen Dateien
      description: >-
        Verkünden der Absicht, die laufende Massendatenlieferung abzubrechen und die übertragenen Dateien zu verwerfen
      operationId: einreichungAbbrechen
      parameters:
        - name: datentransfernummer
          in: path
          description: 'Die Datentransfernummer, die die Transaktion identifiziert'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Anfrage erfolgreich
        '400':
          description: Ungültige Datentransfernummer
        '401':
          description: Ungültiger Authorization Header
        '409':
          description: Ungültige Schnittstellen Version
        '410':
          description: Datentransfer wurde bereits beendet
        '424':
          description: Der Datenübermittler ist dem Vorgang nicht zugeordnet
        '500':
          description: Interner Fehler
  /dip/md/v2_1/{datentransfernummer}/protocol:
    get:
      tags:
        - MDSProviderV2_1
      summary: Abruf des Ergebnisprotokolls
      description: Abruf des Ergebnisprotokolls
      operationId: protokollAbrufen
      parameters:
        - name: datentransfernummer
          in: path
          description: 'Die Datentransfernummer, die die Transaktion identifiziert'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Anfrage erfolgreich
          content:
            application/octet-stream:
              schema:
                type: InputStream
        '400':
          description: Ungültige Datentransfernummer
        '401':
          description: Ungültiger Authorization Header
        '409':
          description: Ungültige Schnittstellen Version
        '404':
          description: Protokoll liegt nicht vor
        '424':
          description: Der Datenübermittler ist dem Vorgang nicht zugeordnet
        '500':
          description: Interner Fehler
    patch:
      tags:
        - MDSProviderV2_1
      summary: Erhalt des Protokolls bestätigen
      description: Erhalt des Protokolls bestätigen
      operationId: protokollErhalten
      parameters:
        - name: datentransfernummer
          in: path
          description: 'Die Datentransfernummer, die die Transaktion identifiziert'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Anfrage erfolgreich
        '400':
          description: Ungültige Datentransfernummer
        '401':
          description: Ungültiger Authorization Header
        '404':
          description: Protokoll liegt nicht vor
        '424':
          description: Der Datenübermittler ist dem Vorgang nicht zugeordnet
        '500':
          description: Interner Fehler
  /dip/md/v2_1/protocolnumbers:
    get:
      tags:
        - MDSProviderV2_1
      summary: Abruf einer Liste aller Datentransfernummern mit verfügbarem Protokoll
      description: Abruf einer Liste aller Datentransfernummern mit verfügbarem Protokoll
      operationId: alleProtokollnummern
      responses:
        '200':
          description: Anfrage erfolgreich
          content:
            application/octet-stream:
              schema:
                type: InputStream
        '401':
          description: Ungültiger Authorization Header
        '500':
          description: Interner Fehler
  /dip/md/v2_1/opennumbers:
    get:
      tags:
        - MDSProviderV2_1
      summary: Abruf einer Liste aller Datentransfernummern, für die das Protokoll noch aussteht
      description: Abruf einer Liste aller Datentransfernummern, für die das Protokoll noch aussteht
      operationId: alleOffenenDatentransfernummern
      responses:
        '200':
          description: Anfrage erfolgreich
          content:
            application/octet-stream:
              schema:
                type: InputStream
        '401':
          description: Ungültiger Authorization Header
        '500':
          description: Interner Fehler